version: "3.9"
services:
  app:
    build: 
      context: '.'
      dockerfile: Dockerfile
    command: ./dev-docker-entrypoint.sh
    volumes: 
      - ./:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    # Expose port 3000.
    ports:
      - "3000:3000"
    depends_on:
      - database
    image: todo-dev:1.0.0
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
  database:
    image: postgres:13.2
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: test_db_password
volumes:
  db_data:
  bundle:
  node_modules: